### ISSUE TITLE
GSoC: add integrate Casbin doc for web frameworks

### ISSUE THREAD

**Issue by nodece** [casbin/node-casbin#130]
Provides integrate doc in Casbin-Website for web framework.

## Things to do

- [ ] express-authz
- [ ] koa-authz
- [ ] egg-authz
- [ ] nest-authz
- [ ] hapi-authz
- [ ] meteor-authz

**Comment by romitkarmakar** [comment]
@nodece I would like to work on this issue. Could you tell me whether i have to write integration doc about this or, tutorial about how to use them ?

**Comment by romitkarmakar** [comment]
@nodece Please review this PR: [casbin-website#53](https://github.com/casbin/casbin-website/pull/53). 
Added this middlewares
- [x] express-authz
- [x] koa-authz
- [x] egg-authz
- [ ]  nest-authz
 - [ ] hapi-authz
 - [ ] meteor-authz

Last three couldn't be added due to a lack of official middlewares.

**Comment by Cronus1007** [comment]
@nodece Shall I implement this one.
