### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by guissy** [casbin/node-casbin#19]
rvals[j] maybe undefined

https://github.com/casbin/node-casbin/blob/8f0315c62a4167c497723bccce4240bdf52cdb10/src/coreEnforcer.ts#L321
https://github.com/casbin/node-casbin/blob/8f0315c62a4167c497723bccce4240bdf52cdb10/src/coreEnforcer.ts#L325

**Comment by hsluoyz** [comment]
I think it's not bad to expose these ``array index out of bounds`` errors to the developers for two reasons:

1. It is caused by compile-time error. The exception will alert the developer. If we cover the error, we gain nothing but make the developer unaware of what's going wrong.
2. No additional checks, so performance is improved.
