### ISSUE TITLE
Support a full set of Sync API like enforcer.enforce()

### ISSUE THREAD

**Issue by hsluoyz** [casbin/node-casbin#224]
Some background: https://github.com/casbin/node-casbin/issues/152

As Node-Casbin not only targets for Node.js but also targets for browser, the current async API is not very friendly for browser use (like conditional rendering a React component).

So we need to prepare a full set of Sync API. This is an very important feature for Casbin to be used smoothly in browser.

**Comment by hsluoyz** [comment]
@divy9881 @zhmushan

**Comment by nodece** [comment]
> the current async API is not very friendly for browser use (like conditional rendering a React component).

I don't quite agree with you, now most frameworks support asynchrony very well.

React: https://codesandbox.io/s/quirky-panini-58lo2?file=/src/App.tsx

**Comment by hsluoyz** [comment]
> > the current async API is not very friendly for browser use (like conditional rendering a React component).
> 
> I don't quite agree with you, now most frameworks support asynchrony very well.
> 
> React: https://codesandbox.io/s/quirky-panini-58lo2?file=/src/App.tsx

Adding @fgblomqvist to the thread, in case I'm misconveying something.

**Comment by fgblomqvist** [comment]
> > the current async API is not very friendly for browser use (like conditional rendering a React component).
> 
> I don't quite agree with you, now most frameworks support asynchrony very well.
> 
> React: https://codesandbox.io/s/quirky-panini-58lo2?file=/src/App.tsx

There's no doubt that the support is there, but I think what you missed is the part about using it smoothly. In your example, you need:

1. To declare a new hook for every single permission you want to check.
2. To wrap a component that checks permissions in a suspense boundary

Both of those are acceptable if you actually are dealing with async resources (like an API), since there's no way around that. However, if you're dealing with sync resources the added complexity is a bit much imo. You'd essentially be adding code that is useless since all the methods node-casbin ends up calling in reality are actually synchronous.

Also worth noting is that suspense for data fetching is still considered an experimental feature, so I'm not sure a lot of people would be willing to implement it in a production-level application. But yes, sure, you can still achieve what you want using old-fashioned useState and useEffect hooks, but that still involves more state and more loading-checking than a simple synchronous call.

**Comment by hsluoyz** [comment]
@fgblomqvist I'm not a React expert either. But is it possible to solve the current problem if we wrap the Node-Casbin into a component like `react-casbin`?

**Comment by fgblomqvist** [comment]
Building e.g. a conditional-render component around node-casbin would solve/simplify a part of the problem, but there are still more complex rendering patterns (e.g. conditional classes) where a component wouldn't help.

If supporting a sync API would be a definite no then I think the best approach would be to have a hook, such as `usePermissions` that would take e.g. the subject and a list of resources/actions to test against and then provide a bool map of which items in that list passed the enforcer. However, such a hook would need to be quite flexible as well due to people using casbin differently so ultimately it feels quite pointless to offer that hook OOB.

**Comment by hsluoyz** [comment]
@fgblomqvist I'm just considering all options. Sync API is still one of our top choices.

BTW, could you give some comments for: https://github.com/casbin/node-casbin/pull/226#issuecomment-761828296 ?

**Comment by MohdImran001** [comment]
@hsluoyz and @fgblomqvist, I would like to work on it.

**Comment by MohdImran001** [comment]
@hsluoyz, is this issue open for contributions ???

**Comment by nodece** [comment]
Hello everyone, I do not intend to support this feature:

- Most libraries or frameworks can fully support asynchronous calls
- Have to use async API, use Promise implement
