### ISSUE TITLE
Latest release 5.34.0 The matcher no longer short-circuit evaluation if it comes across a truthy expression

### ISSUE THREAD

**Issue by tomfriedhof** [casbin/node-casbin#493]
If you have a matcher that has multiple conditions such as the one below:

```
m = (r.user == p.user && r.path == p.resource && r.action == p.action) || \
    (r.input.service == p.svc && r.input.region == p.region && r.action == p.method)
```

The new evaluator will still attempt to evaluate the second expression even if the first express was truthy. This is an issue because in same cause a prop in the `input` object is not passed to `enforce` sometimes.

In version 5.32.0 and earlier the matcher will short-circuit once it finds a match.

**Comment by hsluoyz** [comment]
@tomfriedhof this is because we switched the evaluator from the official expression-eval v5.0.0 to our own fork @casbin/expression-eval v5.2.0 (which is yet the same code as the official package v5.0.1, we only changed the CI code in next versions) in the PR: https://github.com/casbin/node-casbin/pull/489 . 

So I suspect the changes happen between v5.0.0 and v5.0.1 in the official package.

@tomfriedhof can you test it by switching to v5.0.1 to see if it is also wrong?
