### ISSUE TITLE
Suggestion: add official docs to repo

### ISSUE THREAD

**Issue by dreamdevil00** [casbin/node-casbin#58]
It's more convenient for user to contribute to docs if the official docs are in the repo.
FYI, please checkout [typeorm](https://github.com/typeorm/typeorm)

**Comment by hsluoyz** [comment]
Hi @dreamdevil00 , it's kind of difficult for Casbin to put docs into source code repo, because Casbin is a federation of projects implemented in different languages: Casbin (Go), jCasbin (Java), Node-Casbin (Node.js), etc. We have a universal docs site here: https://casbin.org/. The source is: https://github.com/casbin/casbin-website

Any suggestions?

**Comment by hsluoyz** [comment]
Closed as stale.
